image: fedora/latest
packages:
  - podman
sources:
  - https://git.sr.ht/~icikowski/account-center
submitter:
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/heads/main
      - "refs/tags/*"
secrets:
  - 65d4bf79-0440-47b0-8462-0dec7b6880bd # ~/.token_dockerhub
  - faa31eef-4d36-41ea-b68b-08167fb89e5f # ~/.token_github
tasks:
  - build-and-push: |
      cd account-center

      case "$GIT_REF" in
      refs/heads/main)
        image_tag=dev
        latest_tag=
        ;;
      refs/tags/*)
        image_tag="${GIT_REF#refs/tags/}"
        latest_tag=latest
        ;;
      *)
        echo "unsupported ref: $GIT_REF" >&2
        exit 1
        ;;
      esac

      dockerhub_token_file="$HOME/.token_dockerhub"
      github_token_file="$HOME/.token_github"

      set +x
      test -r "$dockerhub_token_file" || { echo "missing $dockerhub_token_file" >&2; exit 1; }
      test -r "$github_token_file" || { echo "missing $github_token_file" >&2; exit 1; }
      podman login --username icikowski --password-stdin docker.io < "$dockerhub_token_file" >/dev/null
      podman login --username Icikowski --password-stdin ghcr.io < "$github_token_file" >/dev/null
      set -x

      build_version=$(git describe --tags --exact-match ${GIT_REF:-HEAD} 2>/dev/null || echo "dev")
      build_commit=$(git rev-parse --verify ${GIT_REF:-HEAD})
      build_timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      build_short_ref=$(git describe --tags --exact-match ${GIT_REF:-HEAD} 2>/dev/null || echo "main")
      local_image="localhost/account-center:${image_tag}"

      podman build \
        --file Containerfile \
        --build-arg BUILD_VERSION="$build_version" \
        --build-arg BUILD_COMMIT="$build_commit" \
        --build-arg BUILD_TIMESTAMP="$build_timestamp" \
        --build-arg BUILD_SHORT_REF="$build_short_ref" \
        --tag "$local_image" .

      for repository in \
        icikowski/account-center \
        ghcr.io/icikowski/account-center
      do
        remote_image="${repository}:${image_tag}"
        podman tag "$local_image" "$remote_image"
        podman push "$remote_image"

        if test -n "$latest_tag"; then
          latest_image="${repository}:${latest_tag}"
          podman tag "$local_image" "$latest_image"
          podman push "$latest_image"
        fi
      done
